### Lecture 11b

In [5]:
import numpy as np
from numpy import linalg as LA

In [7]:
mat = np.arange(1, 13).reshape(3, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
mat[2, 2:]

array([11, 12])

In [12]:
mat[:2, [1, 2]]

array([[2, 3],
       [6, 7]])

In [16]:
mat[1:, ::-2]

array([[ 8,  6],
       [12, 10]])

In [20]:
arr = np.arange(0, 100, 10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
arr[[4, 1, 8]] # indicate which indeces you want

array([40, 10, 80])

In [24]:
mat[1:, [3, 1]]

array([[ 8,  6],
       [12, 10]])

### Special Matrices

In [27]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros([2, 4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
np.ones([2, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
23 * np.ones([2, 4])

array([[23., 23., 23., 23.],
       [23., 23., 23., 23.]])

In [37]:
23 + np.zeros([2, 4])

array([[23., 23., 23., 23.],
       [23., 23., 23., 23.]])

In [39]:
np.full([2, 4], 23)

array([[23, 23, 23, 23],
       [23, 23, 23, 23]])

In [43]:
np.eye(4) # Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Sorting Arrays

In [48]:
arr6 = np.arange(6).reshape(2, 3)
arr6

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
arr10 = 10 - arr6 # vectorized subtraction
arr10

array([[10,  9,  8],
       [ 7,  6,  5]])

In [56]:
arr10.sort() #destructive operation, it will modity the array

In [58]:
arr10 # default sort by row

array([[ 8,  9, 10],
       [ 5,  6,  7]])

In [62]:
arr10.sort(axis=0) # sorted by column
arr10

array([[ 5,  6,  7],
       [ 8,  9, 10]])

### Random Numbers

In [65]:
np.random.random()

0.4105814988646088

In [71]:
np.random.random(4) # you can add number and dimension to it 

array([0.7878607 , 0.65061502, 0.05667341, 0.33839812])

In [69]:
np.random.random([2, 4])

array([[0.95180618, 0.22656746, 0.45911349, 0.72374347],
       [0.8224728 , 0.61582224, 0.28845008, 0.76206795]])

Numpy `randint` does not include the right endpoint (use half-open intervals)

In [84]:
np.random.randint(1, 6, [2, 4]) # excludes 6 at the right endpoint

array([[2, 4, 5, 2],
       [4, 1, 3, 4]])

In [94]:
np.random.choice([5, 6, 7], 4)

array([7, 5, 5, 6])

### Boolean Indexing

In [133]:
np.random.seed(23)

In [135]:
arr_rand = np.random.randint(5, 20, [2, 4])
arr_rand

array([[ 8, 11, 13, 14],
       [11, 13, 18, 17]])

In [137]:
arr_rand > 15

array([[False, False, False, False],
       [False, False,  True,  True]])

In [139]:
arr_rand[arr_rand > 15] #pull out elements that return true

array([18, 17])

In [141]:
arr_rand % 2 == 1

array([[False,  True,  True, False],
       [ True,  True, False,  True]])

In [143]:
arr_rand[arr_rand % 2 == 1] # select all odd elements of array, return 1D array

array([11, 13, 11, 13, 17])

### Boolean operators
Combining boolean expressions:  
* Enclose each expression in parentheses
* Use ~ & | ^ instead of `not`, `and`, `or`

In [149]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [151]:
mat = 5 * mat
mat

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [153]:
mat <= 30

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [157]:
~(mat > 30) # same as above

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

Elements that are <= 30 and end in digit 5

In [162]:
mat[(mat <= 30) & (mat % 10 == 5)]

array([ 5, 15, 25])

### Views vs Copies of Arrays

In [165]:
arr = np.arange(0, 100, 10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [169]:
arr2 = arr[1:4]
arr2

array([10, 20, 30])

In [171]:
arr2 *= 10
arr2

array([100, 200, 300])

In [173]:
arr

array([  0, 100, 200, 300,  40,  50,  60,  70,  80,  90])

In [177]:
arr3 = arr[-3:].copy()
arr3

array([70, 80, 90])

In [179]:
arr3 += 5

In [181]:
arr3

array([75, 85, 95])

In [183]:
arr

array([  0, 100, 200, 300,  40,  50,  60,  70,  80,  90])

### Linear Systems of Equations

Suppose you have $p$ pigs, $c$ chickens, and $g$ goats. Set up equations to calculate the total number of heads $H$, legs $L$, and weight $W$. 

```
p + c + g = H
4p + 2c + 4g = L
400p + 5c + 160g = W
```

Let $p = 12$, $c = 23$, and $g = 5$. Calculate H, L W

In [189]:
anim = np.array([12, 23, 5])
anim

array([12, 23,  5])

In [195]:
coefH = np.ones(3)
coefL = np.array([4, 2, 4])
coefW = np.array([400, 5, 160])

In [207]:
H = anim.sum()
H

40

In [209]:
L = (coefL * anim).sum()
L

114

In [211]:
np.dot(coefL, anim)

114

In [221]:
W = (coefW * anim).sum()
W

5715

Create a matrix of coefH, coefL, coefW. 

In [235]:
anim_mat = np.vstack([coefH, coefL, coefW])
anim_mat

array([[  1.,   1.,   1.],
       [  4.,   2.,   4.],
       [400.,   5., 160.]])

In [239]:
HLW = anim_mat @ anim
HLW

array([  40.,  114., 5715.])

In [242]:
LA.solve(anim_mat, HLW)

array([12., 23.,  5.])

In [244]:
LA.inv(anim_mat) @ HLW

array([12., 23.,  5.])

### Example
A Farmer owns 52 pigs, chickens, goats in total. There are 3 times as many pigs as chickens and goats combined. There are 194 leg in all. How many of each animal are there?

```
p +  c  +  g = 52
p -  3c - 3g = 0
4p + 2c + 4g = 194
```

In [251]:
coeffs = np.array([ [1, 1, 1], [1, -3, -3], [4, 2, 4]])
coeffs

array([[ 1,  1,  1],
       [ 1, -3, -3],
       [ 4,  2,  4]])

In [253]:
total = np.array([52, 0, 194])

In [257]:
LA.solve(coeffs, total)

array([39.,  7.,  6.])

In [261]:
LA.inv(coeffs) @ total

array([39.,  7.,  6.])