### Lecture 15b

In [2]:
import math
import random
import numpy as np

In [42]:
arr = np.arange(2, 25, 2).reshape(3, 4)
arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [48]:
arr[2, -2::-2]

array([22, 18])

In [52]:
arr[:, 2]

array([ 6, 14, 22])

In [70]:
arr[1:, :-3:-1]

array([[16, 14],
       [24, 22]])

In [72]:
arr[1:, 3:1:-1]

array([[16, 14],
       [24, 22]])

### Continued Fractions

In [80]:
def cont_frac(numlist):
    '''Return the value of a finite simple continued fraction give numlist'''
    if len(numlist) == 1:
        return numlist[0]
    else:
        return numlist[0] + 1 / cont_frac(numlist[1:])

In [82]:
cont_frac([2, 4, 4, 4, 4])

2.236065573770492

In [86]:
cont_frac([1, 1, 1, 1, 1, 1])

1.625

### CU Semester Code
2024 fall: 2247  
2023 spring: 2231  
1985 summer: 1854  

Write a function **`sem_code(year, sem)` and returns the CU 4-digit code as an integer.

In [136]:
# string version
def sem_code(year, sem):
    sem_dict = {'fall':7, 'spring':1, 'summer':4}
    years = str(year)[0] + str(year)[2:]
    return int(years + str(sem_dict[sem]))
    # return 10* int(return_year) + sem_dict[sem]

In [138]:
sem_code(2024, 'fall')

2247

In [140]:
# non-string version
def sem_code(year, sem):
    sem_dict = {'fall':7, 'spring':1, 'summer':4}

    first_digit = year // 1000
    last2_digits = year % 100
    sem_digit = sem_dict[sem]

    return first_digit * 1000 + last2_digits * 10 + sem_digit

In [142]:
sem_code(1985, 'summer')

1854

### Min-Max Scaling 
Write a function `normalize(arr)` that scales an array of number to the range 0 to 1 and the remaining numbers are scaled proportionally. 

In [151]:
def normalize(arr):
    minval = arr.min() #shift all numbers by minval
    maxval = arr.max()
    arr_range = maxval - minval # scale factor

    return (arr - minval) / arr_range

In [164]:
np.random.seed(20)
arr1 = np.random.randint(1, 11, 5)
arr2 = np.random.randint(1, 11, 5)

In [166]:
arr1

array([ 4, 10,  5,  7,  8])

In [168]:
arr2

array([3, 1, 7, 9, 6])

In [170]:
normalize(arr1)

array([0.        , 1.        , 0.16666667, 0.5       , 0.66666667])

In [172]:
normalize(arr2)

array([0.25 , 0.   , 0.75 , 1.   , 0.625])

In [176]:
# code tracing
def func(x):
    if x < 2:
        return 0
    else:
        return 10 + func(x-1)

func(4)

30