# Recitation 14

In [7]:
import numpy as np

For this assignment, **use numpy vectorization for all exercises**. Do not use loops or list comprehensions unless instructed to do so.

### Useful Numpy Functions

* `np.sum(arr)` or `arr.sum()` returns the sum of the elements in `arr`.
* `np.prod(arr)` or `arr.prod()` returns the product of the elements in `arr`.
  
* `np.any(arr)` or `arr.any()` returns `True` if any element in `arr` is `True`.
* `np.all(arr)` or `arr.all()` returns `True` if all elements in `arr` are `True`.
  
* `np.argmin(arr)` or `arr.argmin()` returns the index or indices of the smallest element.
* `np.argmax(arr)` or `arr.argmax()` returns the index or indices of the largest element.

* `np.repeat(arr, ct)` duplicates each element of the array `ct` times. Example: `np.repeat(np.arange(1, 3), 3)` returns `array([1, 1, 1, 2, 2, 2])`.

* `np.where(condition, a, b)` returns `a` if `condition` is `True` and returns `b` otherwise (similar to the one-line `if` statement).
* `np.select(conditions, choices, default=0)` is similar to `np.where` except it allows for a list of `conditions` and a corresponding list of `choices`. The function returns the element in `choices` that matches the first condition that is `True`. If all conditions are `False`, the `default` value is returned.

### Odd Elements
Write a function **`is_odd_elts(arr)`** that takes a numpy array (of any shape) of integers and returns a new array of the same shape with True for each odd element and False for each even element.

Example: 
```
is_odd_elts(np.array([[2, 5], [-1, 3]]))
```
returns
```
array([[False,  True],
       [ True,  True]])
```

In [11]:
def is_odd_elts(arr):
    return arr % 2 == 1

In [12]:
is_odd_elts(np.array([[2, 5], [-1, 3]]))

array([[False,  True],
       [ True,  True]])

Write a function **`odd_elts(arr)`** that takes a numpy array (of any shape) of integers and returns a 1-D array containing only the numbers that are odd.

Example: 
```
odd_elts(np.array([[2, 5], [-1, 3]]))
```
returns
```
array([ 5, -1,  3])
```

In [14]:
def odd_elts(arr):
    return arr[is_odd_elts(arr)]

In [15]:
odd_elts(np.array([[2, 5], [-1, 3]]))

array([ 5, -1,  3])

### Add Index to Array Elements
Write a function **`add_index(arr)`** that takes a 1-D array of numbers and returns a new array, adding 1 to the first element of nums, 2 to the second element, 3 to the third element, etc.

Example:
```
add_index(np.array([-3, 10.5, 100]))
```
returns
```
array([ -2. ,  12.5, 103. ])
```

In [17]:
def add_index(arr):
    add_num = np.arange(1, arr.size +1)
    return arr + add_num

In [18]:
add_index(np.array([-3, 10.5, 100]))

array([ -2. ,  12.5, 103. ])

### Remainder Sum
When the integer $12$ is divided by the numbers $1, 2, \ldots, 8$, the sum of the remainders is 

$$ 0+0+0+0+2+0+5+4 = 11. $$

Write a function **`remainder_sum(num, max_divisor)`** that returns the sum of the remainders when `num` is divided by the numbers from $1$ to `max_divisor`. Assume that the input values are positive integers.

Example:  
`remainder_sum(12, 8)` returns `11`.

In [20]:
def remainder_sum(num, max_divisor):
    divisor = np.arange(1, max_divisor+1)
    return np.sum(num%divisor)

In [21]:
remainder_sum(12, 8)

11

### Half Pi

$$\frac{\pi}{2} = \frac 21\cdot \frac 23\cdot \frac 43\cdot \frac 45\cdot \frac 65\cdot \frac 67 \cdots$$

Write a function **`half_pi(n)`** that returns the product of the first `n` fractions in this pattern.

In [23]:
def half_pi(n):
    even = np.arange(2, 2 * n + 1, 2)
    odd = np.arange(3, 2 * n + 2, 2)
    top = np.repeat(even, 2)[:n]
    bottom = np.concatenate(([1], np.repeat(odd, 2)))[:n]
    return np.prod(top / bottom)

In [24]:
half_pi(9)

1.6511967750062986

### Copying an Array with Conditions
Write a function **`copy_3s(arr)`** that takes an array of integers and returns a new array copying the numbers that end in 3 or are divisible by 3. All other numbers are replaced with 0. (*Hint:* Recall that the numpy logical operators `&` and `|` are used in place of `and` and `or`.)

Example:
```
copy_3s(np.arange(11, 21))
```
returns 
```
array([ 0, 12, 13,  0, 15,  0,  0, 18,  0,  0])
```

In [59]:
def copy_3s(arr):
    result = np.where((arr % 10 == 3) | (arr % 3 == 0), arr, 0)
    return result

In [61]:
copy_3s(np.arange(11, 21))

array([ 0, 12, 13,  0, 15,  0,  0, 18,  0,  0])

### Moo Oink
*Moo Oink* is a counting game where players take turns counting starting with $1, 2, \ldots$. For any number divisible by 3, the player says 'moo' instead of the number. For any number divisible by 4, the player says 'oink'. For any number divisible by 3 and 4, the player says 'moo oink'. 

Numpy does not allow the mixing of string and numerical data types in an array. For this exercise, **replace the 3 strings with these numerical codes**:

|String|Code|  
|:--|:--:|  
|'moo'|-3|  
|'oink'|-4|  
|'moo oink'|-12|

Write a function **`moo_oink(n)`** that returns an array of the responses counting from 1 to `n`. You may assume that `n` is a positive integer.

Example:
```
moo_oink(13)
```
returns
```
array([  1,   2,  -3,  -4,   5,  -3,   7,  -4,  -3,  10,  11, -12,  13])
```

In [69]:
def moo_oink(n):
    arr = np.arange(1, n + 1)
    
    result = np.where((arr % 3 == 0) & (arr % 4 == 0), -12,
             np.where(arr % 3 == 0, -3,
             np.where(arr % 4 == 0, -4, arr)))
    
    return result

In [71]:
moo_oink(13)

array([  1,   2,  -3,  -4,   5,  -3,   7,  -4,  -3,  10,  11, -12,  13])

### A Sequence

Consider the function 
  $$ f(a) = \begin{cases}
      1 & \text{if }a=1,\\
      1 + 3a & \text{if }a\text{ is odd}\text{ and }a> 1\\
      a/ 2 & \text{if }a\text{ is even}.
  \end{cases} $$ 
Write a function **`afunc(a)`** that returns the value of $f$ for positive integer $a$. 

Starting with $a$, if we apply $f$ repeatedly, using each output value as the next input value, the sequence produced will eventually reach the number $1$. For example starting $a=5$, the sequence produced is $5, 16, 8, 4, 2, 1$, with a sequence length of $6$.

Write a function **`afunc_seqlen(n)`** that returns an array containing the sequence length for each number from $1$ to $n$. The function should begin with an array containing the numbers from $1$ to $n$, then use a single loop to apply `afunc()` to each number in the array repeatedly until all starting values have reached $1$. (Do not use nested or multiple loops.) For each number, the function keeps track of the iteration count before $1$ is reached.

For example, for `n=5`, the return value is
```
array([1, 2, 8, 3, 6])
```
because the function begins with an array of the numbers from $1$ to $5$, then repeatedly applies `afunc()` to each number until all sequences reach $1$. The process looks like
```
 1  2  3  4  5
 1  1 10  2 16
 1  1  5  1  8
 1  1 16  1  4
 1  1  8  1  2
 1  1  4  1  1
 1  1  2  1  1
 1  1  1  1  1
```

In [ ]:
def afunc(a):
    if a == 1:
        return 1
    elif a % 2 ==1:
        return 1 + 3*a
    else:
        return a / 2

In [80]:
def afunc_seqlen(n):
    arr = np.arange(1, n + 1)
    lengths = np.ones_like(arr)
    
    while np.any(arr != 1):
        lengths[arr != 1] += 1
        arr = np.where(arr != 1, np.where(arr % 2 == 0, arr // 2, 3 * arr + 1), arr)
    
    return lengths

In [82]:
afunc_seqlen(5)

array([1, 2, 8, 3, 6])

___

# Extra Problems
Work on these problems after completing the previous exercises.

### Closest Point
Write a function **`closest(pt, pts)`** that identifies the point in a set of `pts` that is closest to a given `pt`. Assume that `pt` contains the coordinates of a point in $n$-D space and `pts` is a 2-D array of $k$ points with shape $(k,n)$. Each row of `pts` contains the $n$-D coordinates of a point in the set. To measure closeness, use the square of the distance between two points: $ (\Delta x_1)^2 + (\Delta x_2)^2 + \cdots + (\Delta x_3)^2$.

You may wish to use the `np.apply_along_axis(func, axis, arr, *args)` function which applies a function to `arr` along the given `axis`, where `*args` represents extra arguments to pass to `func`.

Example: 
```
pt = np.array([6, 1])
pts = np.array([ [-4, -5], [-3, 3], [-1, 0], [ 2, 4], [ 4, -5] ])
closest(pt, pts)
```
returns
```
array([2, 4])
```
and
```
pt = np.array([3, -5, 1])
pts = np.array([ [-4, -5, 2], [-2, -3, 0], [1, 0, -2] ])
closest(pt, pts)
```
returns
```
array([-2, -3,  0])
```


### Prime Spiral

The *prime spiral*, also known as *Ulam's spiral*, shows the distribution of prime numbers when the positive integers are arranged in a spiral pattern such as the one below:
```
[[37 36 35 34 33 32 31]
 [38 17 16 15 14 13 30]
 [39 18  5  4  3 12 29]
 [40 19  6  1  2 11 28]
 [41 20  7  8  9 10 27]
 [42 21 22 23 24 25 26]
 [43 44 45 46 47 48 49]]
```
There are many instances where prime numbers appear on a diagonal. For example the 4 primes 19, 7, 23, and 47 lie on a diagonal.

Write a function **`prime_spiral(spiral_file)`** that reads in a number spiral from a file, and returns an array with the number `1` marking the prime numbers and the number `0` marking the non-primes. You may call `np.loadtxt(spiral_file, dtype=int)` and use the `is_prime(num)` function defined below.

The files `spiral7.txt` and `spiral30.txt` are available for testing. For example: `print(prime_spiral('spiral7.txt'))` displays
```
[[1 0 0 0 0 0 1]
 [0 1 0 0 0 1 0]
 [0 0 1 0 1 0 1]
 [0 1 0 0 1 1 0]
 [1 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [1 0 0 0 1 0 0]]
```


In [122]:
def is_prime(num):
    if num == 1:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False   
    return True

### Moo Oink Variation
A variation of the *Moo Oink* counting game assigns 'moo' to any number divisible by 3 *or* contains the digit 3. It assigns 'oink' to any number divisible by 4 *or* contains the digit 4. It assigns 'moo oink' to any number satisfying both of the previous conditions.

Write a function **`moo_oink_var(n)`** that returns an array of the responses counting from 1 to `n`. You may assume that `n` is a positive integer. Again replace the 3 strings with these numerical codes:

|String|Code|  
|:--|:--:|  
|'moo'|-3|  
|'oink'|-4|  
|'moo oink'|-12|

Example:
```
moo_oink_var(15)
```
returns
```
array([  1,   2,  -3,  -4,   5,  -3,   7,  -4,  -3,  10,  11, -12,  -3, -4, -3])